add 2 homework
babenko-alex-pdffiller/gocourse02 pull request #1
Opened 2024-08-15 11:05 UTC by babenko-alex-pdffiller

2024-08-15 11:16 UTC, alexandear requested changes

2024-08-15 11:16 UTC, alexandear commented on tasks/homework.go
> +	rand.Seed(time.Now().UnixNano())
Ось цей рядок можна видалити, використавши імпорт `math/rand/v2` замість `math/rand`.

https://go.dev/blog/randv2

2024-08-15 11:16 UTC, alexandear commented on tasks/homework.go
> +)
Чи можемо ми використати typed constant тут?
```suggestion
type AnimalType string

const (
	Lion   AnimalType = "Lion"
	Tiger  AnimalType = "Tiger"
	Duck   AnimalType = "Duck"
	Monkey AnimalType = "Monkey"
)
```

Про константи можна почитати тут https://go.dev/doc/effective_go#constants і тут https://go.dev/blog/constants

2024-08-15 11:16 UTC, alexandear commented on tasks/homework.go
> +func (cage *Cage) openCage() {
Ось цей метод не використовується ніде в `main`? Бажано використати.

Також, можемо його перейменувати без втрати читабельності: "openCage" -> `open`.

2024-08-15 14:08 UTC, babenko-alex-pdffiller commented on tasks/homework.go
> +	rand.Seed(time.Now().UnixNano())
замінив на `math/rand/v2`

2024-08-15 14:09 UTC, babenko-alex-pdffiller commented on tasks/homework.go
> +func (cage *Cage) openCage() {
так, забув про нього, перейменував та використав

2024-08-15 14:15 UTC, babenko-alex-pdffiller commented on tasks/homework.go
> +)
так, замінив

2024-08-15 15:31 UTC, alexandear requested changes
Останні штрихи.

2024-08-15 15:31 UTC, alexandear commented on tasks/homework.go
> +		if isOpen == true {
📝 зазвичай пишуть простіше
```go
if isOpen {
```

2024-08-15 15:31 UTC, alexandear commented on tasks/homework.go
> +	animalsNames := [4]AnimalType{Lion, Tiger, Duck, Monkey}
📝 можна прибрати одну `s` всередині:
```suggestion
	animalNames := [4]AnimalType{Lion, Tiger, Duck, Monkey}
```

2024-08-15 15:31 UTC, alexandear commented on tasks/homework.go
> +func (a *Animal) makeFree() {
Я би перейменував на `escape`, ніби звір втікає.

2024-08-15 15:31 UTC, alexandear commented on tasks/homework.go
> +func (keper *ZooKeeper) SendToCage(animal *Animal, cage *Cage) {
📝 напевно краще `PutToCage`

2024-08-15 15:31 UTC, alexandear commented on tasks/homework.go
> +			animals[i].IsFree = true
В кожної тварини є метод "втекти", може краще його використати?
```suggestion
			animals[i].makeFree()
```

2024-08-16 07:56 UTC, babenko-alex-pdffiller commented on tasks/homework.go
> +		if isOpen == true {
так, згоден, то для наглядності

2024-08-16 07:57 UTC, babenko-alex-pdffiller commented on tasks/homework.go
> +	animalsNames := [4]AnimalType{Lion, Tiger, Duck, Monkey}
прибрав

2024-08-16 08:01 UTC, babenko-alex-pdffiller commented on tasks/homework.go
> +func (a *Animal) makeFree() {
перейменував на runАway

2024-08-16 08:04 UTC, babenko-alex-pdffiller commented on tasks/homework.go
> +			animals[i].IsFree = true
так, додав виклик

2024-08-16 09:47 UTC, alexandear approved these changes
LGTM

2024-08-16 09:47 UTC, merged